2020-04-21 20:57:25,788 base_request.py[line:66]ERROR Invalid URL 'testapicxcm.cxjk.com/interface/home/bodyChanges': No schema supplied. Perhaps you meant http://testapicxcm.cxjk.com/interface/home/bodyChanges?
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_request.py", line 51, in __http_post
    response = s.post(url=interface_url, headers=headerdata, data=temp_interface_param, verify=False, timeout=10)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Python360\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "D:\Python360\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'testapicxcm.cxjk.com/interface/home/bodyChanges': No schema supplied. Perhaps you meant http://testapicxcm.cxjk.com/interface/home/bodyChanges?
2020-04-21 20:57:50,501 base_request.py[line:66]ERROR Invalid URL 'testapicxcm.cxjk.com/interface/home/bodyChanges': No schema supplied. Perhaps you meant http://testapicxcm.cxjk.com/interface/home/bodyChanges?
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_request.py", line 51, in __http_post
    response = s.post(url=interface_url, headers=headerdata, data=temp_interface_param, verify=False, timeout=10)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Python360\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "D:\Python360\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'testapicxcm.cxjk.com/interface/home/bodyChanges': No schema supplied. Perhaps you meant http://testapicxcm.cxjk.com/interface/home/bodyChanges?
2020-04-21 20:58:48,888 base_request.py[line:66]ERROR Invalid URL 'testapicxcm.cxjk.com/interface/home/bodyChanges': No schema supplied. Perhaps you meant http://testapicxcm.cxjk.com/interface/home/bodyChanges?
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_request.py", line 51, in __http_post
    response = s.post(url=interface_url, headers=headerdata, data=temp_interface_param, verify=False, timeout=10)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "D:\Python360\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\Python360\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "D:\Python360\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'testapicxcm.cxjk.com/interface/home/bodyChanges': No schema supplied. Perhaps you meant http://testapicxcm.cxjk.com/interface/home/bodyChanges?
2020-04-21 21:57:15,978 base_compare.py[line:104]ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 89, in compare_params_complete
    if params_to_compare.startswith('[') and isinstance(params_to_compare, str):  # 判断用例中预期结果是否为列表
AttributeError: 'list' object has no attribute 'startswith'
2020-04-21 21:57:16,052 connectionpool.py[line:437]DEBUG https://testapicxcm.cxjk.com:443 "POST /interface/home/bodyChanges HTTP/1.1" 200 141288
2020-04-21 21:57:16,101 base_compare.py[line:104]ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 89, in compare_params_complete
    if params_to_compare.startswith('[') and isinstance(params_to_compare, str):  # 判断用例中预期结果是否为列表
AttributeError: 'list' object has no attribute 'startswith'
2020-04-21 21:59:49,126 base_compare.py[line:104]ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 89, in compare_params_complete
    if params_to_compare.startswith('[') and isinstance(params_to_compare, str):  # 判断用例中预期结果是否为列表
AttributeError: 'list' object has no attribute 'startswith'
2020-04-21 21:59:49,173 connectionpool.py[line:437]DEBUG https://testapicxcm.cxjk.com:443 "POST /interface/home/bodyChanges HTTP/1.1" 200 141288
2020-04-21 21:59:49,222 base_compare.py[line:104]ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 89, in compare_params_complete
    if params_to_compare.startswith('[') and isinstance(params_to_compare, str):  # 判断用例中预期结果是否为列表
AttributeError: 'list' object has no attribute 'startswith'
2020-04-21 22:00:41,608 base_compare.py[line:104]ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 89, in compare_params_complete
    if params_to_compare.startswith('[') and isinstance(params_to_compare, str):  # 判断用例中预期结果是否为列表
AttributeError: 'list' object has no attribute 'startswith'
2020-04-21 22:02:06,998 base_compare.py[line:109]ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 89, in compare_params_complete
    if params_to_compare.startswith('[') and isinstance(params_to_compare, str):  # 判断用例中预期结果是否为列表
AttributeError: 'list' object has no attribute 'startswith'
2020-04-21 22:02:07,042 connectionpool.py[line:437]DEBUG https://testapicxcm.cxjk.com:443 "POST /interface/home/bodyChanges HTTP/1.1" 200 141288
2020-04-21 22:02:07,090 base_compare.py[line:109]ERROR 'list' object has no attribute 'startswith'
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 89, in compare_params_complete
    if params_to_compare.startswith('[') and isinstance(params_to_compare, str):  # 判断用例中预期结果是否为列表
AttributeError: 'list' object has no attribute 'startswith'
2020-04-21 22:07:41,290 base_compare.py[line:110]ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 90, in compare_params_complete
    list_params_to_compare = eval(params_to_compare)  # 将数据库表unicode编码数据转换成原列表
TypeError: eval() arg 1 must be a string, bytes or code object
2020-04-21 22:07:41,337 connectionpool.py[line:437]DEBUG https://testapicxcm.cxjk.com:443 "POST /interface/home/bodyChanges HTTP/1.1" 200 141288
2020-04-21 22:07:41,389 base_compare.py[line:110]ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "D:\Api_project\CX_Mother_Baby1\common\base_compare.py", line 90, in compare_params_complete
    list_params_to_compare = eval(params_to_compare)  # 将数据库表unicode编码数据转换成原列表
TypeError: eval() arg 1 must be a string, bytes or code object
